# Generated by Django 3.0.7 on 2021-03-03 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='URLName',
            field=models.SlugField(default='/', max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default='description', max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
